services:
  # Main web service combining nginx and app
  - type: web
    name: spectrum-sandbox
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SPECTRUM_VERSION
        value: v0.1.0-beta
      - key: RENDER_EXTERNAL_URL
        sync: false
    
    # Health check for monitoring
    healthCheckPath: /health
    
    # Resource allocation (free tier)
    plan: free
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build settings
    buildCommand: ""
    
    # Scaling
    numInstances: 1
    
    # Regions
    region: oregon